server:
  port: 8080
  servlet:
    context-path: /CitiProject




mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml # mybatis配置文件所在路径
  type-aliases-package: com.pojo                    # 定义VO包
  mapper-locations:                                      # 所有的mapper映射文件
    - classpath:mybatis/mapper/*.xml



spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test2?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: password_1
    driver-class-name: com.mysql.jdbc.Driver
    dbcp2:                                             # 进行数据库连接池的配置
      min-idle: 5                                      # 数据库连接池的最小维持连接数
      initial-size: 5                                  # 初始化提供的连接数
      max-total: 5                                     # 最大的连接数
      max-wait-millis: 200                             # 等待连接获取的最大超时时间

