spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test_DB?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    schema: classpath:/org/springframework/batch/core/schema-mysql.sql

  batch:
    initialize-schema: always
    job:
      enabled: false
#      names: parentJob






